#!/bin/sh

splint_params='-Iinclude/generic -Iinclude/internal -export-local'
splint_params_posix='+posixstrictlib'
splint_params_curie='+nolib'

splint ${splint_params} ${splint_params_curie} $(find ./include/generic ./include/internal ./src/generic \( -name "*.c" -o -name "*.h" \))
splint ${splint_params} ${splint_params_posix} src/posix/*.c
splint ${splint_params} ${splint_params_posix} src/valgrind/*.c

#for i in tests/*.c; do
#  splint ${splint_params} ${splint_params_curie} "${i}"
#done
