.TH ICEMAKE 1 "APRIL 2009" Curie "Curie Developers Manual"

.SH NAME
ice \- pretty-printing icemake wrapper

.SH SYNOPSIS
.BI "ice [ " icemake-options " ]"

.SH DESCRIPTION
.B ice
is a simple wrapper for icemake, which makes icemake's output somewhat prettier
and easier to follow. Instead of flooding your terminal with s-expressions,
you get a progress bar with a short indication of which stage of compilation
the programme is currently in.

Apart from the obvious use of the programme, this should also provide a nice
example of how to work with curie and it's s-expression code.

.SH OPTIONS
All parameters are passed to icemake verbatim, so see
.BR icemake (1)
for a summary of command line options.

.SH BUGS
.I Host System Compatibility
.RS
The programme will link and compile fine on all target systems, but it only
produces output on systems where libsyscall provides a sys_write() function.
Most notably this affects Microsoft Windows hosts, regardless of toolchain used
to compile the programme. This limitation will be fixed in a future release.
.RE

.SH AUTHOR
Magnus Deininger <magnus.deininger@student.uni-tuebingen.de>

.SH SEE ALSO
.BR icemake (1),
.BR icemake.sx (5)
