.TH ICEMAKE.SX 5 "JULY 2009" Curie "Curie Developers Manual"

.SH NAME
icemake.sx \- build description file for icemake

.SH DESCRIPTION
.B icemake.sx
is a text file containing data in s-expression form for icemake to use when
building a project. The file is a sequence of definitions that describe
programmes and libraries through the code and addon files they are to be built
from.

.SH Build Targets
From icemake's point of view, each base element in the icemake.sx file
represents a potential build target.

...

.SH AUTHOR
Magnus Deininger <magnus.deininger@student.uni-tuebingen.de>

.SH SEE ALSO
.BR icemake (1),
.BR ice (1)
